name: Renovate

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch: {} # allows manual testing

jobs:
  update-docker:
    permissions:
      contents: write # Needed to push branches and commits
      pull-requests: write # Needed to create PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Test dependencies
        run: npm run test:prepare

      - name: Update Makefile Docker versions
        id: update
        run: npm run update-docker-versions

      - name: Create Pull Request
        if: steps.update.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.update.outputs.branch }}
          commit-message: ${{ steps.update.outputs.title }}
          title: ${{ steps.update.outputs.title }}
          body: |
            ## Docker Images Updated

            ${{ steps.update.outputs.summary }}
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
